### ISSUE TITLE
Comcast-Anna Gohman

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/Content-Team#22]
https://drive.google.com/drive/folders/1of1lENOxMzqsboLFknAn1cr5b94NX2ye?usp=sharing

**Comment by bryanace53** [comment]
Hey Brett,

I updated zenhub on where I am with the content. I exported all the videos without confirming the new elements let me know if you like them. Like I mention in our text I do not have any more space on the google drive if you can please fix it that would be great !

**Comment by bryanace53** [comment]
https://drive.google.com/drive/u/3/folders/1kkCVcc0aq08BwiGUeZX20ftdbpaNREeR

**Comment by jaahmuhl** [comment]
Blurb: 

How do you build a successful college career that sets you up for your first job? Approach it like you would when you are building an investment portfolio. That's according to Anna Gohman, the Executive Director for Strategy & Business Operations at Comcast. 


Interviewer: (Brett Hummel)

#promazo, #promazoexecinterviews, #comcast, #careerswitching, #firstjob

**Comment by jaahmuhl** [comment]
@bryanace53 The second question needs to be changed because right now it does not match with what she is saying.![Anna Gohmann Question 2.png](https://images.zenhubusercontent.com/5cb3b35dd74bd07972cea86e/c41b8f0d-a2b1-462e-be57-710f4609f814)

**Comment by bryanace53** [comment]
Video is fixed 

https://drive.google.com/drive/u/3/folders/1kkCVcc0aq08BwiGUeZX20ftdbpaNREeR

**Comment by jaahmuhl** [comment]
Ok but its not in the new video??
@bryanace53

**Comment by bryanace53** [comment]
Do you want me to put her video in the new look? I thought I just needed to
fix the title. I can easily change it but I just want to confirm the look
with you during our meeting.

**Comment by jaahmuhl** [comment]
@bryanace53 this still isn't fixed. You need to change the second question to the text I've post here.

**Comment by bryanace53** [comment]
https://drive.google.com/drive/u/3/folders/1kkCVcc0aq08BwiGUeZX20ftdbpaNREeR

Try this link it should have the new video
